id = "zed-image-input"
name = "Zed Image Input"
version = "0.1.0"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "Input images in the assistant panel"
repository = "https://github.com/your-username/zed-image-input"
[slash_commands.image]
description = "Input an image in the assistant panel"
requires_argument = true
